import {today,addDays,addMonths} from './domain.mjs';
export function demoWorkspace(){
  const user={id:'demo-admin',name:'Anita Sharma',username:'anita',area:'Rampur · Demonstration',role:'admin'},asha={id:'demo-asha',name:'Sunita Devi',username:'sunita',area:'Rampur, Ward 04',role:'asha'},other={id:'demo-other',name:'Meena Kumari',username:'meena',area:'Rampur, Ward 05',role:'asha'};
  const now=today(),records=[];let seq=0;
  const put=(kind,data,owner=asha.id,id=`demo-${++seq}`)=>{records.push({id,kind,ownerId:owner,data,version:1,updatedAt:new Date().toISOString(),deleted:false});return id;};
  const homes=[['Sharma family','12, Peepal Street','Ward 04'],['Devi family','7, School Road','Ward 04'],['Kumar family','23, Temple Lane','Ward 04'],['Singh family','9, Lake Road','Ward 05'],['Yadav family','31, Market Street','Ward 05'],['Verma family','16, Anganwadi Lane','Ward 04']];
  const names=[['Ramesh Sharma','Male',43],['Priya Sharma','Female',27],['Aarav Sharma','Male',3],['Kamla Devi','Female',82],['Sunil Devi','Male',39],['Neha Devi','Female',25],['Arjun Kumar','Male',31],['Pooja Kumar','Female',28],['Anaya Kumar','Female',0],['Vikram Singh','Male',55],['Sita Singh','Female',49],['Isha Singh','Female',12],['Mohan Yadav','Male',61],['Geeta Yadav','Female',57],['Kabir Yadav','Male',4],['Rajesh Verma','Male',36],['Kavita Verma','Female',29],['Riya Verma','Female',1]];
  const mids=[];homes.forEach((h,i)=>{const owner=[3,4].includes(i)?other.id:asha.id,id=put('household',{name:h[0],address:h[1],locality:h[2]},owner);names.slice(i*3,i*3+3).forEach((n,j)=>{const dob=n[2]===0?addDays(now,-14):addMonths(now,-n[2]*12-2);mids.push(put('member',{householdId:id,name:n[0],sex:n[1],dob,estimatedAge:'',residence:'Resident',registeredOn:addDays(now,-60),relationship:j===0?'Household contact':j===1?'Spouse / relative':'Child / relative',phone:'',abha:'',abhaStatus:'Not recorded',notes:'Fictional demonstration record.'},owner));});});
  put('pregnancy',{memberId:mids[1],registeredOn:addDays(now,-90),lmp:addDays(now,-190),edd:addDays(now,90),status:'Active',risk:'Routine follow-up',source:'Demo only',notes:'Next antenatal follow-up planned.'});
  put('pregnancy',{memberId:mids[5],registeredOn:addDays(now,-70),lmp:addDays(now,-230),edd:addDays(now,50),status:'Active',risk:'Review requested',source:'Demo only',notes:'Discuss recorded referral with supervisor.'});
  for(const [i,name] of [[0,'Hypertension'],[3,'Diabetes'],[9,'Hypertension'],[12,'Diabetes'],[13,'Hypertension']]){const m=records.find(r=>r.id===mids[i]);put('condition',{memberId:m.id,name,status:'Confirmed',date:addDays(now,-40),source:'Fictional clinic record',notes:'Demonstration only'},m.ownerId);}
  for(const [i,program,days,status]of [[1,'ANC',0,'Planned'],[8,'HBNC',0,'Planned'],[3,'NCD',-2,'Planned'],[5,'ANC',2,'Planned'],[17,'HBYC',1,'Planned'],[14,'Immunisation',3,'Planned'],[0,'NCD',-1,'Completed'],[8,'HBNC',-7,'Completed']]){const m=records.find(r=>r.id===mids[i]);put('visit',{memberId:m.id,program,dueDate:addDays(now,days),status,actualDate:status==='Completed'?addDays(now,days):'',notes:'Fictional visit. Use locally approved clinical forms in a live workspace.',checklist:[]},m.ownerId);}
  put('event',{memberId:mids[8],type:'Birth',date:addDays(now,-14),status:'Confirmed',source:'Fictional birth report',notes:'Demo only'});
  return {user,users:[user,asha,other],records,outbox:[],lastSync:new Date().toISOString()};
}
